#!/bin/bash
g++ -std=c++1y main.cpp magazine.cpp UI.cpp tile.cpp zombie.cpp spriteHandler.cpp vector.cpp cursor.cpp sprite.cpp bullet.cpp player.cpp sourcery.cpp zombiespawner.cpp -lSDL2 -lSDL2_ttf -lSDL2main -o game -O3

